export const URU_DEPARTMENTS = [
  { value: "ARTIGAS", label: "Artigas" },
  { value: "CANELONES", label: "Canelones" },
  { value: "CERRO_LARGO", label: "Cerro Largo" },
  { value: "COLONIA", label: "Colonia" },
  { value: "DURAZNO", label: "Durazno" },
  { value: "FLORES", label: "Flores" },
  { value: "FLORIDA", label: "Florida" },
  { value: "LAVALLEJA", label: "Lavalleja" },
  { value: "MALDONADO", label: "Maldonado" },
  { value: "MONTEVIDEO", label: "Montevideo" },
  { value: "PAYSANDU", label: "Paysandú" },
  { value: "RIO_NEGRO", label: "Río Negro" },
  { value: "RIVERA", label: "Rivera" },
  { value: "ROCHA", label: "Rocha" },
  { value: "SALTO", label: "Salto" },
  { value: "SAN_JOSE", label: "San José" },
  { value: "SORIANO", label: "Soriano" },
  { value: "TACUAREMBO", label: "Tacuarembó" },
  { value: "TREINTA_Y_TRES", label: "Treinta y Tres" },
];
